# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20, unique=True)),
                ('yoc1', models.IntegerField()),
                ('yoc2', models.IntegerField()),
                ('board1', models.CharField(max_length=200)),
                ('board2', models.CharField(max_length=200)),
                ('percentage1', models.IntegerField()),
                ('percentage2', models.IntegerField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
