# Generated by Django 2.0.dev20170613061616 on 2017-06-16 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='userID',
        ),
    ]
