# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_remove_education_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='address',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='college',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='company',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='contact',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='dob',
            field=models.DateField(default='N/A'),
        ),
        migrations.AddField(
            model_name='education',
            name='duration',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='git_hub',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='linked_in',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='education',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='work',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
